In [ ]:
import pandas as pd
import numpy as np
import nltk
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score,classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import torch
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
data = pd.read_csv("/content/processed_data.csv")
data.head()

,QuestionText,Category,Answer,Question_for_classification,Answer_for_classification,Question_for_QA,Answer_for_QA,Question_for_translation,Answer_for_translation,Question_tokens,Answer_tokens,Question_tokens_no_stopwords,Answer_tokens_no_stopwords,Question_tokens_stemmed,Answer_tokens_stemmed,Question_text_no_stopwords,Question_text_stemmed,Answer_text_no_stopwords,Answer_text_stemmed
0,أيهما أفضل الدراسة في السابق أم في الوقت الحالي؟,التعليم,الدراسة في الوقت الحالي تعتبر أفضل بسبب توفر ا...,ايهما افضل الدراسة في السابق ام في الوقت الحالي,الدراسة في الوقت الحالي تعتبر افضل بسبب توفر ا...,ايهما افضل الدراسة في السابق ام في الوقت الحالي؟,الدراسة في الوقت الحالي تعتبر افضل بسبب توفر ا...,ايهما افضل الدراسة في السابق ام في الوقت الحالي؟,الدراسة في الوقت الحالي تعتبر افضل بسبب توفر ا...,"['ايهما', 'افضل', 'الدراسة', 'في', 'السابق', '...","['الدراسة', 'في', 'الوقت', 'الحالي', 'تعتبر', ...","['ايهما', 'افضل', 'الدراسة', 'السابق', 'ام', '...","['الدراسة', 'الوقت', 'الحالي', 'تعتبر', 'افضل'...","['ايه', 'فضل', 'درس', 'سبق', 'ام', 'وقت', 'الح...","['درس', 'وقت', 'الحالي', 'عبر', 'فضل', 'سبب', ...",ايهما افضل الدراسة السابق ام الوقت الحالي,ايه فضل درس سبق ام وقت الحالي,الدراسة الوقت الحالي تعتبر افضل بسبب توفر التك...,درس وقت الحالي عبر فضل سبب وفر كنولوج ورد علم حدث
1,أليس القطن عماد الثروة في مصر؟,الاقتصاد والعمل,القطن يعتبر من أهم المنتجات الزراعية في مصر، و...,اليس القطن عماد الثروة في مصر,القطن يعتبر من اهم المنتجات الزراعية في مصر وي...,اليس القطن عماد الثروة في مصر؟,القطن يعتبر من اهم المنتجات الزراعية في مصر، و...,اليس القطن عماد الثروة في مصر؟,القطن يعتبر من اهم المنتجات الزراعية في مصر، و...,"['اليس', 'القطن', 'عماد', 'الثروة', 'في', 'مصر']","['القطن', 'يعتبر', 'من', 'اهم', 'المنتجات', 'ا...","['اليس', 'القطن', 'عماد', 'الثروة', 'مصر']","['القطن', 'يعتبر', 'من', 'اهم', 'المنتجات', 'ا...","['الس', 'قطن', 'عمد', 'ثرة', 'مصر']","['قطن', 'عبر', 'من', 'اهم', 'نتج', 'زرع', 'مصر...",اليس القطن عماد الثروة مصر,الس قطن عمد ثرة مصر,القطن يعتبر من اهم المنتجات الزراعية مصر ويعد ...,قطن عبر من اهم نتج زرع مصر يعد من عمد ريس قصد صري
2,أتصعد الشمس من الشرق؟,التعليم,الشمس تصعد من الشرق.,اتصعد الشمس من الشرق,الشمس تصعد من الشرق,اتصعد الشمس من الشرق؟,الشمس تصعد من الشرق.,اتصعد الشمس من الشرق؟,الشمس تصعد من الشرق.,"['اتصعد', 'الشمس', 'من', 'الشرق']","['الشمس', 'تصعد', 'من', 'الشرق']","['اتصعد', 'الشمس', 'من', 'الشرق']","['الشمس', 'تصعد', 'من', 'الشرق']","['صعد', 'شمس', 'من', 'شرق']","['شمس', 'صعد', 'من', 'شرق']",اتصعد الشمس من الشرق,صعد شمس من شرق,الشمس تصعد من الشرق,شمس صعد من شرق
3,أتعرف البكتيريا بأنها كائنات حية دقيقة؟,التعليم,البكتيريا تُعرف بأنها كائنات حية دقيقة.,اتعرف البكتيريا بانها كاينات حية دقيقة,البكتيريا تعرف بانها كاينات حية دقيقة,اتعرف البكتيريا بانها كاينات حية دقيقة؟,البكتيريا تعرف بانها كاينات حية دقيقة.,اتعرف البكتيريا بانها كاينات حية دقيقة؟,البكتيريا تعرف بانها كاينات حية دقيقة.,"['اتعرف', 'البكتيريا', 'بانها', 'كاينات', 'حية...","['البكتيريا', 'تعرف', 'بانها', 'كاينات', 'حية'...","['اتعرف', 'البكتيريا', 'بانها', 'كاينات', 'حية...","['البكتيريا', 'تعرف', 'بانها', 'كاينات', 'حية'...","['عرف', 'كتر', 'بان', 'كين', 'حية', 'دقق']","['كتر', 'عرف', 'بان', 'كين', 'حية', 'دقق']",اتعرف البكتيريا بانها كاينات حية دقيقة,عرف كتر بان كين حية دقق,البكتيريا تعرف بانها كاينات حية دقيقة,كتر عرف بان كين حية دقق
4,أيتكون الهواء أساساً من النيتروجين؟,التعليم,الهواء يتكون أساساً من النيتروجين.,ايتكون الهوا اساسا من النيتروجين,الهوا يتكون اساسا من النيتروجين,ايتكون الهوا اساسا من النيتروجين؟,الهوا يتكون اساسا من النيتروجين.,ايتكون الهوا اساسا من النيتروجين؟,الهوا يتكون اساسا من النيتروجين.,"['ايتكون', 'الهوا', 'اساسا', 'من', 'النيتروجين']","['الهوا', 'يتكون', 'اساسا', 'من', 'النيتروجين']","['ايتكون', 'الهوا', 'اساسا', 'من', 'النيتروجين']","['الهوا', 'يتكون', 'اساسا', 'من', 'النيتروجين']","['ايت', 'هوا', 'سسا', 'من', 'ترج']","['هوا', 'يتك', 'سسا', 'من', 'ترج']",ايتكون الهوا اساسا من النيتروجين,ايت هوا سسا من ترج,الهوا يتكون اساسا من النيتروجين,هوا يتك سسا من ترج

In [ ]:
data['Category'].value_counts()

Category
الثقافة             725
التعليم             600
العلوم              597
الصحة               537
البيئة والطاقة      500
التكنولوجيا         439
التاريخ             402
الاقتصاد والعمل     290
الجغرافيا           203
السياسة والقانون    194
الدين               114
الرياضة              67
البيولوجيا           50
الترفيه              37
السفر والسياحة       33
التطوع               25
علم الاجتماع          8
Name: count, dtype: int64

In [ ]:
le = LabelEncoder()
y = le.fit_transform(data["Category"])

In [ ]:
X_bert = np.load("/content/bert_embeddings.npy")
X_qwen = np.load("/content/qwen_embeddings.npy")
X_e5 = np.load("/content/e5_embeddings.npy")
X_bge = np.load("/content/bge_embeddings.npy")

X_fasttext_no_stop = np.load("/content/fasttext_no_stop_embeddings.npy")
X_fasttext_stemmed = np.load("/content/fasttext_stemmed_embeddings.npy")

X_sg_no_stop = np.load("/content/sg_no_stop_embeddings.npy")
X_sg_stemmed = np.load("/content/sg_stemmed_embeddings.npy")

X_cbow_no_stop = np.load("/content/cbow_no_stop_embeddings.npy")
X_cbow_stemmed = np.load("/content/cbow_stemmed_embeddings.npy")

X_sg_trained = np.load("/content/sg_trained_embeddings.npy")
X_cbow_trained = np.load("/content/cbow_trained_embeddings.npy")

In [ ]:
embedding_features = {
    "BERT": X_bert,
    "QWEN": X_qwen,
    "E5": X_e5,
    "BGE": X_bge,
    "FastText No Stop": X_fasttext_no_stop,
    "FastText Stemmed": X_fasttext_stemmed,
    "SG No Stop": X_sg_no_stop,
    "SG Stemmed": X_sg_stemmed,
    "CBOW No Stop": X_cbow_no_stop,
    "CBOW Stemmed": X_cbow_stemmed,
    "Word2Vec SG Trained": X_sg_trained,
    "Word2Vec CBOW Trained": X_cbow_trained
}

In [ ]:
models = {
    "SVM": SVC(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "GaussianNB": GaussianNB(),
    "Random Forest": RandomForestClassifier(random_state=42)
}

In [ ]:
results = []
for feature_name, X in embedding_features.items():
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        results.append({
            "Feature": feature_name,
            "Model": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, average="weighted"),
            "Recall": recall_score(y_test, y_pred, average="weighted"),
            "F1-score": f1_score(y_test, y_pred, average="weighted")
        })

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="Accuracy",ascending=False).reset_index(drop=True)
results_df

,Feature,Model,Accuracy,Precision,Recall,F1-score
0,QWEN,SVM,0.784456,0.788256,0.784456,0.782389
1,E5,Logistic Regression,0.757513,0.758434,0.757513,0.756245
2,BERT,SVM,0.756477,0.760221,0.756477,0.751870
3,BERT,Logistic Regression,0.754404,0.754319,0.754404,0.753040
4,BGE,SVM,0.752332,0.754335,0.752332,0.747765
5,BGE,Logistic Regression,0.736788,0.736757,0.736788,0.735551
6,QWEN,Logistic Regression,0.720207,0.721877,0.720207,0.719426
7,E5,SVM,0.713990,0.712397,0.713990,0.702381
8,BGE,GaussianNB,0.709845,0.725882,0.709845,0.708495
9,QWEN,GaussianNB,0.676684,0.687375,0.676684,0.675571
10,BERT,Random Forest,0.674611,0.700265,0.674611,0.665223
11,QWEN,Random Forest,0.672539,0.697191,0.672539,0.660560
12,E5,Random Forest,0.658031,0.685079,0.658031,0.644222
13,BGE,Random Forest,0.646632,0.683616,0.646632,0.634178
14,E5,GaussianNB,0.638342,0.653244,0.638342,0.639512
15,BERT,GaussianNB,0.613472,0.619207,0.613472,0.608496
16,SG Stemmed,Random Forest,0.412435,0.415340,0.412435,0.393711
17,SG No Stop,Random Forest,0.409326,0.419547,0.409326,0.396747
18,FastText No Stop,Random Forest,0.405181,0.427017,0.405181,0.391815
19,FastText Stemmed,Random Forest,0.403109,0.425028,0.403109,0.387554
20,CBOW Stemmed,Random Forest,0.391710,0.406615,0.391710,0.377053
21,CBOW No Stop,Random Forest,0.391710,0.406615,0.391710,0.377053
22,Word2Vec CBOW Trained,Random Forest,0.381347,0.413787,0.381347,0.367606
23,Word2Vec SG Trained,Random Forest,0.372021,0.384657,0.372021,0.361089
24,CBOW No Stop,Logistic Regression,0.322280,0.314021,0.322280,0.311842
25,CBOW Stemmed,Logistic Regression,0.322280,0.314021,0.322280,0.311842
26,SG No Stop,Logistic Regression,0.294301,0.280921,0.294301,0.265018
27,SG Stemmed,Logistic Regression,0.288083,0.268185,0.288083,0.265877
28,SG Stemmed,SVM,0.275648,0.230379,0.275648,0.231873
29,CBOW Stemmed,SVM,0.261140,0.275435,0.261140,0.210580
30,CBOW No Stop,SVM,0.261140,0.275435,0.261140,0.210580
31,FastText No Stop,Logistic Regression,0.251813,0.202197,0.251813,0.203872
32,SG No Stop,SVM,0.241451,0.205567,0.241451,0.185991
33,FastText Stemmed,Logistic Regression,0.237306,0.186017,0.237306,0.189106
34,FastText Stemmed,SVM,0.235233,0.141985,0.235233,0.175524
35,FastText No Stop,SVM,0.235233,0.143656,0.235233,0.171611
36,FastText Stemmed,GaussianNB,0.203109,0.287073,0.203109,0.205025
37,Word2Vec SG Trained,Logistic Regression,0.190674,0.130282,0.190674,0.121781
38,FastText No Stop,GaussianNB,0.190674,0.293812,0.190674,0.185596
39,SG Stemmed,GaussianNB,0.189637,0.256575,0.189637,0.186404
40,SG No Stop,GaussianNB,0.185492,0.274264,0.185492,0.190566
41,CBOW No Stop,GaussianNB,0.173057,0.268328,0.173057,0.184467
42,CBOW Stemmed,GaussianNB,0.173057,0.268328,0.173057,0.184467
43,Word2Vec SG Trained,SVM,0.165803,0.076835,0.165803,0.066287
44,Word2Vec CBOW Trained,Logistic Regression,0.155440,0.065840,0.155440,0.073951
45,Word2Vec CBOW Trained,SVM,0.150259,0.022578,0.150259,0.039257
46,Word2Vec SG Trained,GaussianNB,0.069430,0.133199,0.069430,0.056490
47,Word2Vec CBOW Trained,GaussianNB,0.039378,0.027136,0.039378,0.026861

In [ ]:
results_df.to_csv("classification_embeddings_results.csv", index=False)

TF-IDF

In [ ]:
# TF-IDF on cleaned text
vectorizer = TfidfVectorizer()
tfidf_clean = vectorizer.fit_transform(data['Question_for_classification'])
print(tfidf_clean.shape)

(4821, 5952)

In [ ]:
# TF-IDF on no stopwords text
vectorizer = TfidfVectorizer()
tfidf_no_stop = vectorizer.fit_transform(data['Question_text_no_stopwords'])
print(tfidf_no_stop.shape)

(4821, 5856)

In [ ]:
# TF-IDF on stemmed text
vectorizer = TfidfVectorizer()
tfidf_stemmed = vectorizer.fit_transform(data['Question_text_stemmed'])
print(tfidf_stemmed.shape)

(4821, 2414)

BOW

In [ ]:
# BoW Unigram on cleaned text
cv = CountVectorizer(max_features=500,ngram_range=(1,1))
cv1_clean = cv.fit_transform(data['Question_for_classification'])
print(cv1_clean.shape)

(4821, 500)

In [ ]:
# BoW Unigram on no stopwords text
cv = CountVectorizer(max_features=500,ngram_range=(1,1))
cv1_no_stop = cv.fit_transform(data['Question_text_no_stopwords'])
print(cv1_no_stop.shape)

(4821, 500)

In [ ]:
# BoW Unigram on stemmed text
cv = CountVectorizer(max_features=500,ngram_range=(1,1))
cv1_stemmed = cv.fit_transform(data['Question_text_stemmed'])
print(cv1_stemmed.shape)

(4821, 500)

In [ ]:
#  Bigram on cleaned text
cv = CountVectorizer(max_features=500,ngram_range=(2,2))
cv2_clean = cv.fit_transform(data['Question_for_classification'])
print(cv2_clean.shape)

(4821, 500)

In [ ]:
#  Bigram on no stopwords text
cv = CountVectorizer(max_features=500,ngram_range=(2,2))
cv2_no_stop = cv.fit_transform(data['Question_text_no_stopwords'])
print(cv2_no_stop.shape)

(4821, 500)

In [ ]:
#  Bigram on stemmed text
cv = CountVectorizer(max_features=500,ngram_range=(2,2))
cv2_stemmed = cv.fit_transform(data['Question_text_stemmed'])
print(cv2_stemmed.shape)

(4821, 500)

In [ ]:
# Trigram on cleaned text
cv = CountVectorizer(max_features=500,ngram_range=(3,3))
cv3_clean = cv.fit_transform(data['Question_for_classification'])
print(cv3_clean.shape)

(4821, 500)

In [ ]:
# Trigram on no stopwords text
cv = CountVectorizer(max_features=500,ngram_range=(3,3))
cv3_no_stop = cv.fit_transform(data['Question_text_no_stopwords'])
print(cv3_no_stop.shape)

(4821, 500)

In [ ]:
# Trigram on stemmed text
cv = CountVectorizer(max_features=500,ngram_range=(3,3))
cv3_stemmed = cv.fit_transform(data['Question_text_stemmed'])
print(cv3_stemmed.shape)

(4821, 500)

In [ ]:
traditional_features = {
    "TF-IDF Clean": tfidf_clean,
    "TF-IDF No Stop": tfidf_no_stop,
    "TF-IDF Stemmed": tfidf_stemmed,

    "BoW Clean Unigram": cv1_clean,
    "BoW No Stop Unigram": cv1_no_stop,
    "BoW Stemmed Unigram": cv1_stemmed,

    "BoW Clean Bigram": cv2_clean,
    "BoW No Stop Bigram": cv2_no_stop,
    "BoW Stemmed Bigram": cv2_stemmed,

    "BoW Clean Trigram": cv3_clean,
    "BoW No Stop Trigram": cv3_no_stop,
    "BoW Stemmed Trigram": cv3_stemmed
}

In [ ]:
results = []

for feature_name, X in traditional_features.items():
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    for model_name, model in models.items():

        if model_name == "GaussianNB":
            X_train_input = X_train.toarray()
            X_test_input = X_test.toarray()
        else:
            X_train_input = X_train
            X_test_input = X_test

        model.fit(X_train_input, y_train)
        y_pred = model.predict(X_test_input)

        results.append({
            "Technique": feature_name,
            "Classifier": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, average="weighted"),
            "Recall": recall_score(y_test, y_pred, average="weighted"),
            "F1-score": f1_score(y_test, y_pred, average="weighted")
        })

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
traditional_results_df = pd.DataFrame(results)
traditional_results_df = traditional_results_df.sort_values(by="Accuracy",ascending=False).reset_index(drop=True)
traditional_results_df

,Technique,Classifier,Accuracy,Precision,Recall,F1-score
0,TF-IDF Stemmed,SVM,0.699482,0.718652,0.699482,0.697619
1,TF-IDF Stemmed,Logistic Regression,0.683938,0.697894,0.683938,0.678477
2,BoW Stemmed Unigram,Logistic Regression,0.667358,0.670302,0.667358,0.663745
3,TF-IDF Stemmed,Random Forest,0.659067,0.671626,0.659067,0.657541
4,TF-IDF Clean,Logistic Regression,0.655959,0.679162,0.655959,0.648973
5,TF-IDF No Stop,Logistic Regression,0.654922,0.678104,0.654922,0.647503
6,BoW Stemmed Unigram,SVM,0.650777,0.664829,0.650777,0.646702
7,TF-IDF No Stop,SVM,0.650777,0.683611,0.650777,0.646813
8,BoW Stemmed Unigram,Random Forest,0.644560,0.649141,0.644560,0.642689
9,TF-IDF Clean,SVM,0.640415,0.675182,0.640415,0.636322
10,TF-IDF No Stop,Random Forest,0.626943,0.642357,0.626943,0.624118
11,BoW Clean Unigram,Logistic Regression,0.608290,0.615204,0.608290,0.603756
12,BoW No Stop Unigram,Logistic Regression,0.606218,0.615612,0.606218,0.601469
13,TF-IDF Clean,Random Forest,0.606218,0.615326,0.606218,0.603618
14,TF-IDF Clean,GaussianNB,0.603109,0.621441,0.603109,0.605195
15,TF-IDF No Stop,GaussianNB,0.600000,0.620609,0.600000,0.602468
16,BoW No Stop Unigram,SVM,0.585492,0.605388,0.585492,0.580135
17,BoW Clean Unigram,SVM,0.576166,0.600078,0.576166,0.572917
18,BoW Clean Unigram,Random Forest,0.547150,0.551035,0.547150,0.543722
19,BoW No Stop Unigram,Random Forest,0.539896,0.553502,0.539896,0.537880
20,TF-IDF Stemmed,GaussianNB,0.507772,0.540273,0.507772,0.507038
21,BoW Stemmed Bigram,Logistic Regression,0.487047,0.576315,0.487047,0.493356
22,BoW Clean Bigram,Logistic Regression,0.469430,0.554545,0.469430,0.477609
23,BoW No Stop Bigram,Logistic Regression,0.466321,0.584169,0.466321,0.476937
24,BoW Stemmed Bigram,SVM,0.462176,0.543952,0.462176,0.462246
25,BoW Clean Bigram,Random Forest,0.451813,0.538996,0.451813,0.466035
26,BoW Stemmed Bigram,Random Forest,0.450777,0.527764,0.450777,0.460488
27,BoW Clean Bigram,SVM,0.448705,0.550648,0.448705,0.459809
28,BoW No Stop Bigram,SVM,0.443523,0.553899,0.443523,0.446367
29,BoW No Stop Bigram,Random Forest,0.429016,0.528593,0.429016,0.442415
30,BoW Stemmed Unigram,GaussianNB,0.416580,0.490706,0.416580,0.409502
31,BoW Clean Unigram,GaussianNB,0.398964,0.537219,0.398964,0.414266
32,BoW No Stop Unigram,GaussianNB,0.395855,0.539328,0.395855,0.412379
33,BoW Clean Trigram,Logistic Regression,0.348187,0.609574,0.348187,0.355916
34,BoW Clean Trigram,Random Forest,0.339896,0.591666,0.339896,0.347989
35,BoW Stemmed Trigram,Logistic Regression,0.334715,0.594118,0.334715,0.333713
36,BoW Stemmed Trigram,Random Forest,0.327461,0.575425,0.327461,0.323854
37,BoW Clean Trigram,SVM,0.325389,0.573162,0.325389,0.320677
38,BoW Stemmed Trigram,SVM,0.317098,0.570479,0.317098,0.303646
39,BoW No Stop Trigram,Random Forest,0.315026,0.558384,0.315026,0.307078
40,BoW No Stop Trigram,Logistic Regression,0.312953,0.563204,0.312953,0.305663
41,BoW No Stop Trigram,SVM,0.304663,0.542148,0.304663,0.285887
42,BoW Stemmed Bigram,GaussianNB,0.291192,0.589271,0.291192,0.351813
43,BoW Clean Bigram,GaussianNB,0.291192,0.574590,0.291192,0.347114
44,BoW No Stop Bigram,GaussianNB,0.279793,0.598175,0.279793,0.343100
45,BoW Stemmed Trigram,GaussianNB,0.206218,0.625596,0.206218,0.268546
46,BoW Clean Trigram,GaussianNB,0.205181,0.628761,0.205181,0.282222
47,BoW No Stop Trigram,GaussianNB,0.197927,0.600089,0.197927,0.256486

The best classifier was SVM.
The best text representation was TF-IDF with stemming.
The best overall combination was TF-IDF Stemmed + SVM, achieving 68.9% accuracy.
Stemming improved most experiments.
Locally trained Word2Vec embeddings performed poorly due to limited dataset size.
 Bag of Words: unigram achieved the best performance, followed by bigram, while trigram produced the lowest results due to feature sparsity and limited dataset size.

In [ ]:
!pip install transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.11.0+cu128)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate) (1.5.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from datasets import Dataset
from transformers import (AutoTokenizer,AutoModelForSequenceClassification,Trainer,TrainingArguments)

In [ ]:
data = pd.read_csv("processed_data.csv")
data.head()

                                       QuestionText  ...                                Answer_text_stemmed
0  أيهما أفضل الدراسة في السابق أم في الوقت الحالي؟  ...  درس وقت الحالي عبر فضل سبب وفر كنولوج ورد علم حدث
1                    أليس القطن عماد الثروة في مصر؟  ...  قطن عبر من اهم نتج زرع مصر يعد من عمد ريس قصد صري
2                             أتصعد الشمس من الشرق؟  ...                                     شمس صعد من شرق
3           أتعرف البكتيريا بأنها كائنات حية دقيقة؟  ...                            كتر عرف بان كين حية دقق
4               أيتكون الهواء أساساً من النيتروجين؟  ...                                 هوا يتك سسا من ترج

[5 rows x 19 columns]

In [ ]:
label_encoder = LabelEncoder()
data["label"] = label_encoder.fit_transform(data["Category"])
num_labels = len(label_encoder.classes_)
print(num_labels)
print(label_encoder.classes_)

17
['الاقتصاد والعمل' 'البيئة والطاقة' 'البيولوجيا' 'التاريخ' 'الترفيه'
 'التطوع' 'التعليم' 'التكنولوجيا' 'الثقافة' 'الجغرافيا' 'الدين' 'الرياضة'
 'السفر والسياحة' 'السياسة والقانون' 'الصحة' 'العلوم' 'علم الاجتماع']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data["Question_for_classification"],data["label"],test_size=0.2,random_state=42,stratify=data["label"])

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv02")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/384 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/381 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/825k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.64M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
train_encodings = tokenizer(X_train.tolist(),truncation=True,padding=True,max_length=128)
test_encodings = tokenizer(X_test.tolist(),truncation=True,padding=True,max_length=128)

In [ ]:
train_dataset = Dataset.from_dict({
    'input_ids': train_encodings['input_ids'],
    'attention_mask': train_encodings['attention_mask'],
    'labels': y_train.tolist()
})

test_dataset = Dataset.from_dict({
    'input_ids': test_encodings['input_ids'],
    'attention_mask': test_encodings['attention_mask'],
    'labels': y_test.tolist()
})

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained("aubmindlab/bert-base-arabertv02",num_labels=num_labels)

model.safetensors:   0%|          | 0.00/543M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: aubmindlab/bert-base-arabertv02
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
bert.embeddings.position_ids               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
training_args = TrainingArguments(
    output_dir='./bertresults',
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    optim="adamw_torch"
)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=363, training_loss=1.2978033901246127, metrics={'train_runtime': 102.7468, 'train_samples_per_second': 112.587, 'train_steps_per_second': 3.533, 'total_flos': 166473048792960.0, 'train_loss': 1.2978033901246127, 'epoch': 3.0})

In [ ]:
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(axis=1)

In [ ]:
print("BERT Results")
print("Accuracy",accuracy_score(y_test, y_pred))
print("Precision",precision_score(y_test, y_pred, average="weighted"))
print("Recall",recall_score(y_test, y_pred, average="weighted"))
print("F1-score",f1_score(y_test, y_pred, average="weighted"))

BERT Results
Accuracy 0.7502590673575129
Precision 0.7316657363617276
Recall 0.7502590673575129
F1-score 0.7349097123524632

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
X_qwen = np.load("/content/qwen_embeddings.npy")

In [ ]:
le = LabelEncoder()
y = le.fit_transform(data["Category"])

In [ ]:
X_train_qwen, X_test_qwen, y_train, y_test = train_test_split(X_qwen,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
best_model = SVC()
best_model.fit(X_train_qwen, y_train)

SVC()

In [ ]:
import joblib
joblib.dump(best_model, "qwen_svm_classifier.pkl")

['label_encoder.pkl']

In [ ]:
import joblib
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']